// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Gp2ddb8H2Ysmvxnwl4kHeKKrtUsAFQE',
    appId: '1:638038628767:web:93ce0c79c196d8758505aa',
    messagingSenderId: '638038628767',
    projectId: 'checkerchecks-web-app',
    authDomain: 'checkerchecks-web-app.firebaseapp.com',
    storageBucket: 'checkerchecks-web-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmxYvSA_pKvNzbCP2NFmtmUI4anWAjOs',
    appId: '1:638038628767:android:7cc84b6c3a3e84e58505aa',
    messagingSenderId: '638038628767',
    projectId: 'checkerchecks-web-app',
    storageBucket: 'checkerchecks-web-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0JNSX81UHX7PSLIEiSibe5Sixi0Py4RI',
    appId: '1:638038628767:ios:98a5d5655209a8658505aa',
    messagingSenderId: '638038628767',
    projectId: 'checkerchecks-web-app',
    storageBucket: 'checkerchecks-web-app.firebasestorage.app',
    iosBundleId: 'com.checkerchecks.checkerchecks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0JNSX81UHX7PSLIEiSibe5Sixi0Py4RI',
    appId: '1:638038628767:ios:98a5d5655209a8658505aa',
    messagingSenderId: '638038628767',
    projectId: 'checkerchecks-web-app',
    storageBucket: 'checkerchecks-web-app.firebasestorage.app',
    iosBundleId: 'com.checkerchecks.checkerchecks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Gp2ddb8H2Ysmvxnwl4kHeKKrtUsAFQE',
    appId: '1:638038628767:web:908450bccd9fc0218505aa',
    messagingSenderId: '638038628767',
    projectId: 'checkerchecks-web-app',
    authDomain: 'checkerchecks-web-app.firebaseapp.com',
    storageBucket: 'checkerchecks-web-app.firebasestorage.app',
  );
}
